// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240224023543_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71e9cc37-a261-4493-91b3-4f6d1e3cc020"),
                            Description = "This channel is dedicated to DotNet Core",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("a389a51d-d2a7-400e-97ac-e5b299aeba92"),
                            Description = "This channel is dedicated to Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("550afbdf-08b6-4560-b2f0-4f56bffb9d65"),
                            Description = "This channel is dedicated to ReactJs",
                            Name = "ReactJs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
